# Generated by Django 6.0 on 2025-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, help_text='Введите изображение обложки', null=True, upload_to='images', verbose_name='Обложка'),
        ),
    ]
