# Generated by Django 6.0 on 2025-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите число', max_length=5, verbose_name='Это тест')),
            ],
        ),
    ]
