# Generated by Django 6.0 on 2025-12-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_testline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestLine',
        ),
    ]
